### ISSUE TITLE
Horizontal scroll flickering

### ISSUE THREAD

**Issue by ahoys** [ReactUnity/core#23]
Issue:
Horizontal scrollbar(?) is visible in scroll component that should only have vertical scroll enabled by default. Beyond that, the horizontal scrollbar is flickering in VR.

Replication:
1. Create a scroll component `<scroll>...</scroll>`.
2. Look at the component in VR.

![image](https://user-images.githubusercontent.com/14974945/131191099-15d55334-8d19-4a57-92f4-4142b8588fce.png)

Also, can the scroll be stylized? What's the css hook for it? `::-webkit-scrollbar` doesn't seem to be it.

**Comment by ahoys** [comment]
More information: Just noticed that it has got something to do with the menu object constantly turning. I've set the menu to face the player all the time `menuCanvas.transform.LookAt(playerCamera.transform);`

This will enable the flickering.

**Comment by KurtGokhan** [comment]
Scroll is Unity's scroll and it is a bit buggy. Can you try adding some minimal padding inside the scroll component and see if that fixes it?

Styling the scrollbar is something that have been in my mind for a while. I will start working on it.

**Comment by KurtGokhan** [comment]
Scrollbars can be styled with `::scrollbar` and `::scrollbar-thumb` selectors. They can also be positioned with inset (left,right,top,bottom) and width, height properties.

Example:

```
// Make all scrollbars green color
scroll::scrollbar {
  background-color: green;
}

// Place vertical scrollbars on the left and offset by 10px
scroll::scrollbar[vertical] {
  left: 10px;
}
```

Also the scroll component accepts `direction` property now. The value is one of: `both`, `horizontal`, `vertical`, `none`

For example, if you want to disable horizontal scrolling (which would also get rid of flicker):

```
<scroll direction="vertical">
  ...
</scroll>
```

**Comment by ahoys** [comment]
Almost! Now if the scrollable component isn't visible on the first page you see in the UI, the scroll works as described, but if you start directly from an UI view that has a scroll, that scroll still bugs like in the image above. I had no direction attributes set. Simply `<scroll>...</scroll>`.

For example:

- Main menu that has a link into a server browser (a list that's a scroll) -> works fine.
- Menu that starts directly from server browser -> visible white lines.

Also, while testing, this happened once:

![image](https://user-images.githubusercontent.com/14974945/131293790-f4c35b41-8f2e-4f02-9fc4-2c47d9983a4b.png)

The line went behind the UI. It was placed about 1 meters behind the canvas.
It happened while I started from a scrollable view, then went to a non-scrollable view and finally back to the scroll view.

**Comment by KurtGokhan** [comment]
@ahoys  is it possible for you to build the react app and send me the generated javascript file. You can send it to my email.

If you don't want to send it, that is okay. It will probably take me some time to reproduce the issue.

**Comment by ahoys** [comment]
[issue-23.zip](https://github.com/ReactUnity/core/files/7075408/issue-23.zip)

The build file is inside the build dir.

**Comment by KurtGokhan** [comment]
I found the problem quickly thanks to the file you sent.

Seems like there was some kind of a race condition. Tweaking the script execution order a bit fixed the issue. Hopefully it does not break anything else.

Fixed in 0.4.6. At least the flickering issue should be fixed.

**Comment by ahoys** [comment]
Hmm... I'm not sure if the update changed anything. I still see the lines and the horizontal is flickering, while the vertical has troubles in positioning. The latter probably being the bigger problem.

I also tried the direction-attribute and noticed that setting direction vertical didn't remove the horizontal line.

![image](https://user-images.githubusercontent.com/14974945/131323835-3d2f2d2b-1d0c-4889-aa99-f65a1d63b69d.png)

I did the following procedures to update the packages:
`yarn update @reactunity/renderer`
`npx openump-cli add com.reactunity.core` in the project folder.

**Comment by KurtGokhan** [comment]
I found the reason `direction` is not working. But I could not reproduce the wrong scrollbar position issue. What is your Unity version by the way?

**Comment by ahoys** [comment]
I'm using the preview 2021.1.16f1.
My canvas size is 2800x2000, with scaling of 0.001 x and y. I'm not modifying the size of the elements, but I am fading "MainMenu" gameObject in / out and switching its position based on where the player decides to open the menu.

The key thing to reveal the bug seems to be switching between container components with basic React-states. If I open the menu with a scroll view visible, the position of the white lines are about where they're supposed to be (right & bottom), but if I then switch to another view and back, the lines have moved to some other depth level. Repeating this and the lines get more and more offset.

See the full stack below:

![image](https://user-images.githubusercontent.com/14974945/131343794-d1332d39-6bf3-4970-a357-88bf9b07c3c2.png)

![image](https://user-images.githubusercontent.com/14974945/131343818-52267881-0bd6-4b33-926e-5e4f171a4f17.png)

![image](https://user-images.githubusercontent.com/14974945/131343840-4e2589bd-c2ac-4ca0-b22f-3328a30c3d00.png)

![image](https://user-images.githubusercontent.com/14974945/131343861-e07aaf9c-2f22-42c8-a929-40ef452388cf.png)

The Background is simply a rawImage behind the canvas, to give the UI a bit elevated 3D-effect.

**Comment by ahoys** [comment]
Upon further testing, the issue seems to be related to the canvas moving in some way. For example using the following script with the MainMenu reveals the issue:

```
using UnityEngine;

public class FaceAtCamera : MonoBehaviour
{
    public Canvas menuCanvas;
    public Camera playerCamera;

    void Update()
    {
        menuCanvas.transform.LookAt(playerCamera.transform);
    }
}

```

**Comment by KurtGokhan** [comment]
Ah, I see the issue now. Somehow Z position of the scrollbar shoots off as you rotate the HMD/menu. I suspected that from the image above.

**Comment by KurtGokhan** [comment]
Should be fixed in 0.4.8

**Comment by ahoys** [comment]
Fixed for vertical scrollbars! The horizontal bars still have the issue, although you can easily avoid it by using direction={"vertical"}

**Comment by KurtGokhan** [comment]
I wasn't able to reproduce the flickering issue but I will do an in-depth debugging later.

**Comment by KurtGokhan** [comment]
I still wasn't able to reproduce this issue. But I fixed some long-standing issues in the scroll component about clipping and masking. So, this issue may already be fixed.

If it's still not fixed, a video of the problem will help greatly.

**Comment by ahoys** [comment]
Tested with 0.5.4. The bug still occurs.
Here's the structure I'm using in this case:
`<scroll><div>...</div><div>...</div></scroll>`
[https://youtu.be/vcYqd9Tjg4A](https://youtu.be/vcYqd9Tjg4A)

Tested with Oculus Rift CV1.

Dependencies:
```
  "dependencies": {
    "@reactunity/renderer": "^0.5.2",
    "react": "^17.0.2"
  },
  "devDependencies": {
    "@reactunity/scripts": "^0.5.0",
    "@types/react": "^17.0.14",
    "typescript": "^4.3.5"
  }
```

**Comment by KurtGokhan** [comment]
Fixed in 0.5.5.

This was a floating point error in Unity's ScrollRect and it happens when canvas is far away from origin, rotated and scaled. [Other people](https://answers.unity.com/questions/1235692/rect-transform-position-keeps-changing-value-rando.html) have also noticed this issue. I could not find a good fix so I added a 1px tolerance to ScrollRect before scrollbar appears.
