### ISSUE TITLE
If resolution of the window is changed, the vh and vw property are not updated

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#48]
I think this might be the only `ReactUnityUIDocument` related.

When you start your application, and you use `100vh` or `100vw` you get a component over the full screen. But after you change the resolution of the window. For example through resolution picker:
![image](https://user-images.githubusercontent.com/5092066/165630365-753a3b1f-19b3-43b9-8267-a601f964908b.png)
Size in pixels of `100vh` or `100vw` property is not updated and left as is.

**Example:** 
We start with a height of 720 pixels. We use 100vh on a div, and this div is set to 720 pixels.
Then we change the size of the window and by extension, its resolution, so the height is now1080 pixels.
But we notice that the div of 100vh is still of size 720 pixels.

**Comment by KurtGokhan** [comment]
Fixed on main branch.

**Comment by KurtGokhan** [comment]
Fixed in v0.10.0

**Comment by Muchaszewski** [comment]
This issue is still reproducible when a custom aspect is selected in the editor:
![image](https://user-images.githubusercontent.com/5092066/167682572-72953e41-fc4a-465a-8480-686dffae1ffc.png)

**Steps to reproduce**
1. Create a component with 100vh
2. Perform code edit (and hot reload)
3. Size of the 100vh is not honored until resolution changes again

![image](https://user-images.githubusercontent.com/5092066/167683026-5f171131-9617-422e-9f8e-0924632c3eae.png)

It looks like it tries to keep the resolution of the editor window instead of set aspect for this given window

**Comment by Muchaszewski** [comment]
I just confirmed that hot-reload brakes this even with "Free Aspect" and the results of the window are unclear to me.
![image](https://user-images.githubusercontent.com/5092066/167683407-2790f038-9e58-4ddb-a367-14b2217b09d4.png)

**Comment by KurtGokhan** [comment]
Can't reproduce. Note that the vw and vh units are based on the root component's size, rather than the editor windows size.
